-- Disposable local database ONLY. Synthetic selected-order fixture; rolled back.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT extensions.plan(40);
SELECT extensions.ok(NOT (SELECT enabled FROM public.pelecard_controlled_live_control),'gate ships disabled');
SELECT extensions.ok(NOT has_table_privilege('authenticated','public.pelecard_controlled_live_control','SELECT'),'browser cannot see key');
SELECT extensions.ok(NOT has_function_privilege('service_role','public.claim_pelecard_controlled_live_init(uuid)','EXECUTE'),'service cannot dispatch');
SELECT extensions.ok(NOT has_function_privilege('pelecard_controlled_live_adapter','public.finalize_pelecard_payment(uuid,text,text,text,numeric,text)','EXECUTE'),'Node cannot finalize');
SELECT extensions.ok(NOT has_function_privilege('authenticated','public.reserve_pelecard_controlled_live(uuid)','EXECUTE'),'browser cannot reserve');
SELECT extensions.ok(NOT has_function_privilege('anon','public.get_pelecard_controlled_live_attempt(uuid)','EXECUTE'),'anonymous cannot see provider identifiers');
SELECT extensions.ok(NOT has_table_privilege('service_role','public.pelecard_controlled_live_control','UPDATE'),'service cannot reset control');
SELECT extensions.ok(NOT EXISTS(SELECT 1 FROM unnest(ARRAY['orders','sales','payment_transactions','accounting_events','accounting_documents']) t WHERE has_table_privilege('pelecard_controlled_live_adapter','public.'||t,'SELECT,INSERT,UPDATE,DELETE')),'Node has no commercial table privileges');
INSERT INTO auth.users(id,email) VALUES ('74000000-0000-4000-8000-000000000001','live-admin@example.test');
SELECT set_config('request.jwt.claims','{"role":"service_role"}',true);
UPDATE public.profiles SET role='admin' WHERE id='74000000-0000-4000-8000-000000000001';
INSERT INTO public.orders(id,order_number,client_name,client_phone,activity_date,num_participants,total_price)
VALUES ('a57ebbc6-47a9-4e74-9208-3340f8508df7','ORD-1039','Synthetic controlled order','0500000000',CURRENT_DATE,1,35);
-- A stale event from before the hold must never acquire a worker lease later.
INSERT INTO public.accounting_events(id,source_type,source_id,purpose,accounting_provider)
VALUES ('74000000-0000-4000-8000-000000000005','order','a57ebbc6-47a9-4e74-9208-3340f8508df7','payment_success','rivhit');
SELECT set_config('request.jwt.claims','{"role":"service_role"}',true);
SELECT extensions.throws_ok($$SELECT public.reserve_pelecard_controlled_live('74000000-0000-4000-8000-000000000001')$$,'23514','controlled_live_disabled','disabled cannot reserve');
UPDATE public.pelecard_controlled_live_control SET enabled=true;
SELECT extensions.throws_ok($$SELECT public.reserve_pelecard_controlled_live('74000000-0000-4000-8000-000000000099')$$,'42501','controlled_live_admin_required','admin required');
UPDATE public.orders SET total_price=36 WHERE order_number='ORD-1039';
SELECT extensions.throws_ok($$SELECT public.reserve_pelecard_controlled_live('74000000-0000-4000-8000-000000000001')$$,'23514','controlled_live_order_not_payable','authoritative amount required');
UPDATE public.orders SET total_price=35 WHERE order_number='ORD-1039';
SELECT extensions.ok((public.reserve_pelecard_controlled_live('74000000-0000-4000-8000-000000000001')->>'created')::boolean,'reserve commercial attempt');
SELECT extensions.ok(NOT (public.reserve_pelecard_controlled_live('74000000-0000-4000-8000-000000000001')->>'created')::boolean,'retry same attempt');
SELECT extensions.is((SELECT count(*) FROM public.get_pelecard_controlled_live_attempt((SELECT payment_id FROM public.pelecard_controlled_live_control))),0::bigint,'lookup unavailable before init identifiers');
UPDATE public.pelecard_controlled_live_control SET enabled=false;
SELECT extensions.is((SELECT count(*) FROM public.claim_pelecard_controlled_live_init((SELECT payment_id FROM public.pelecard_controlled_live_control))),0::bigint,'disabled gate blocks dispatch after reservation');
UPDATE public.pelecard_controlled_live_control SET enabled=true;
SELECT extensions.throws_ok($$SELECT public.complete_pelecard_initiation((SELECT payment_id FROM public.pelecard_controlled_live_control),'74000000-0000-4000-8000-000000000003','https://gateway20.pelecard.biz/PaymentGW?transactionId=74000000-0000-4000-8000-000000000003')$$,'23514','controlled_live_verification_mismatch','generic initiation cannot bypass stored identity');
SELECT extensions.is((SELECT count(*) FROM public.payment_transactions WHERE order_id='a57ebbc6-47a9-4e74-9208-3340f8508df7'),1::bigint,'one ledger row');
SELECT extensions.is((SELECT amount_minor FROM public.claim_pelecard_controlled_live_init((SELECT payment_id FROM public.pelecard_controlled_live_control))),3500,'claim authoritative 3500');
SELECT extensions.is((SELECT count(*) FROM public.claim_pelecard_controlled_live_init((SELECT payment_id FROM public.pelecard_controlled_live_control))),0::bigint,'dispatch cannot repeat');
SELECT extensions.throws_ok($$UPDATE public.pelecard_controlled_live_control SET dispatch_started_at=NULL$$,'23514','controlled_live_identity_immutable','claim never released');
SELECT extensions.throws_ok($$UPDATE public.pelecard_controlled_live_control SET payment_id=NULL$$,'23514','controlled_live_identity_immutable','reservation never reset');
SELECT extensions.throws_ok($$DELETE FROM public.pelecard_controlled_live_control$$,'23514','controlled_live_identity_immutable','control cannot delete');
SELECT extensions.throws_ok($$UPDATE public.payment_transactions SET amount=36 WHERE order_id='a57ebbc6-47a9-4e74-9208-3340f8508df7'$$,'23514','controlled_live_payment_immutable','amount immutable');
SELECT extensions.throws_ok($$UPDATE public.payment_transactions SET checkout_snapshot='{}'::jsonb WHERE order_id='a57ebbc6-47a9-4e74-9208-3340f8508df7'$$,'23514','controlled_live_payment_immutable','snapshot immutable');
SELECT extensions.throws_ok($$UPDATE public.orders SET total_price=36 WHERE order_number='ORD-1039'$$,'23514','order_payment_in_progress','existing order lock preserved');
SELECT extensions.throws_ok($$SELECT public.reserve_pelecard_payment(gen_random_uuid(),'a57ebbc6-47a9-4e74-9208-3340f8508df7','74000000-0000-4000-8000-000000000001','second-controlled',35,'ILS','{}')$$,'23514','controlled_live_attempt_already_reserved','generic reservation cannot create another attempt');
SELECT extensions.throws_ok($$SELECT public.save_pelecard_controlled_live_session((SELECT payment_id FROM public.pelecard_controlled_live_control),'74000000-0000-4000-8000-000000000003','key-1039','https://evil.example/pay')$$,'23514','controlled_live_invalid_session','provider URL restricted');
SELECT extensions.lives_ok($$SELECT public.save_pelecard_controlled_live_session((SELECT payment_id FROM public.pelecard_controlled_live_control),'74000000-0000-4000-8000-000000000003','key-1039','https://gateway20.pelecard.biz/PaymentGW?transactionId=74000000-0000-4000-8000-000000000003')$$,'session saved through existing initiation');
SELECT extensions.is((SELECT transaction_id FROM public.get_pelecard_controlled_live_attempt((SELECT payment_id FROM public.pelecard_controlled_live_control))),'74000000-0000-4000-8000-000000000003','lookup stored identifier');
SELECT extensions.throws_ok($$SELECT public.save_pelecard_controlled_live_session((SELECT payment_id FROM public.pelecard_controlled_live_control),'74000000-0000-4000-8000-000000000003','key-changed','https://gateway20.pelecard.biz/PaymentGW?transactionId=74000000-0000-4000-8000-000000000003')$$,'23514','controlled_live_session_mismatch','identifier immutable');
SELECT extensions.throws_ok($$SELECT public.finalize_pelecard_controlled_live((SELECT payment_id FROM public.pelecard_controlled_live_control),'wrong','approval','000',35,'ILS')$$,'23514','controlled_live_verification_mismatch','provider match required');
SELECT extensions.lives_ok($$SELECT public.finalize_pelecard_controlled_live((SELECT payment_id FROM public.pelecard_controlled_live_control),'74000000-0000-4000-8000-000000000003','approval','000',35,'ILS')$$,'verified payment finalizes');
SELECT extensions.lives_ok($$SELECT public.finalize_pelecard_controlled_live((SELECT payment_id FROM public.pelecard_controlled_live_control),'74000000-0000-4000-8000-000000000003','approval','000',35,'ILS')$$,'finalization idempotent');
SELECT extensions.is((SELECT count(*) FROM public.sales WHERE order_id='a57ebbc6-47a9-4e74-9208-3340f8508df7'),1::bigint,'one sale');
SELECT extensions.is((SELECT count(*) FROM public.accounting_events WHERE source_id=(SELECT payment_id::text FROM public.pelecard_controlled_live_control)),0::bigint,'accounting enqueue permanently held');
UPDATE public.pelecard_controlled_live_control SET enabled=false;
SELECT extensions.ok(public.is_pelecard_controlled_live_accounting_held('A57EBBC6-47A9-4E74-9208-3340F8508DF7'),'hold permanent when disabled and case independent');
SELECT extensions.ok(NOT public.is_pelecard_controlled_live_accounting_held('ordinary-source'),'ordinary accounting unaffected');
SELECT extensions.throws_ok($$SELECT * FROM public.claim_accounting_event('74000000-0000-4000-8000-000000000005','future-worker',300,true)$$,'23514','controlled_live_accounting_hold','future worker cannot claim stale held event');
SELECT extensions.is((SELECT count(*) FROM public.claim_pelecard_controlled_live_init((SELECT payment_id FROM public.pelecard_controlled_live_control))),0::bigint,'finalized attempt never dispatches again');
SELECT extensions.throws_ok($$INSERT INTO public.accounting_documents(provider,account_namespace,accounting_customer_id,source_type,source_id,document_type_key,external_document_type,request_reference,payload_hash) SELECT 'rivhit','test',gen_random_uuid(),'sale',sale_id::text,'payment_success',1,'held','held' FROM public.payment_transactions WHERE id=(SELECT payment_id FROM public.pelecard_controlled_live_control)$$,'23514','controlled_live_accounting_hold','direct sale document blocked before issuance');
SELECT * FROM extensions.finish();
ROLLBACK;
