-- Synthetic local fixtures only. Never run as a production smoke test.
BEGIN;
SET search_path=public,extensions;
SELECT extensions.plan(75);
SELECT extensions.ok(to_regprocedure('public.save_quotation(uuid,uuid,integer,jsonb,uuid,integer,boolean)') IS NOT NULL,'quotation save RPC exists');
INSERT INTO auth.users(id,email) VALUES ('96000000-0000-4000-8000-000000000001','quotation-admin@example.invalid'),('96000000-0000-4000-8000-000000000002','quotation-cashier@example.invalid');
SELECT set_config('request.jwt.claims','{"role":"service_role"}',true);
UPDATE public.profiles SET role=CASE WHEN id='96000000-0000-4000-8000-000000000001' THEN 'admin'::public.user_role ELSE 'cashier'::public.user_role END WHERE id IN ('96000000-0000-4000-8000-000000000001','96000000-0000-4000-8000-000000000002');
SELECT set_config('request.jwt.claims','{"role":"authenticated","sub":"96000000-0000-4000-8000-000000000001"}',true);
SET LOCAL ROLE authenticated;
SELECT public.save_customer('{"display_name":"Original master","contact_name":"Quoted contact","phone":"0501234567","vat_applicable":false,"billing_name":"Original billing"}','96000000-0000-4000-8000-000000000010',NULL);
SELECT set_config('test.data','{"client_name":"Quote override","client_phone":"0501234567","client_email":"quote@example.invalid","organization":"Quoted org","event_date":"2026-11-01","num_participants":10,"selected_activities":[{"item_type":"activity","activity_name":"Deleted historical activity","price_per_person":12.35,"quantity":3,"description":"Saved description"},{"item_type":"product","activity_name":"Historical product","price_per_person":7.5,"quantity":2}],"discount":2.05,"billing_institution_name":"Quoted billing","notes":"Original multiline\nHebrew preserved"}',true);
SELECT set_config('test.q',public.save_quotation('96000000-0000-4000-8000-000000000011',NULL,0,current_setting('test.data')::jsonb,'96000000-0000-4000-8000-000000000010',1,false)::text,true);
SELECT extensions.is((current_setting('test.q')::jsonb->>'final_price')::numeric,50.00::numeric,'server computes full gross and discount');
SELECT extensions.is((current_setting('test.q')::jsonb->>'quotation_version')::integer,1,'first immutable revision');
SELECT extensions.is(current_setting('test.q')::jsonb->>'vat_applicable','false','explicit customer exemption captured');
SELECT extensions.is(public.save_quotation('96000000-0000-4000-8000-000000000011',NULL,0,current_setting('test.data')::jsonb,'96000000-0000-4000-8000-000000000010',1,false),current_setting('test.q')::jsonb,'exact request replay');
SELECT extensions.throws_ok($$SELECT public.save_quotation('96000000-0000-4000-8000-000000000011',NULL,0,'{}',NULL,NULL,false)$$,'PT409','quotation_request_conflict','changed request UUID rejected');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb||'{"final_price":1}',NULL,NULL,false)$$,'22023','invalid_quotation_fields','browser totals forbidden');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb||'{"vat_applicable":true}',NULL,NULL,false)$$,'22023','invalid_quotation_fields','caller VAT forbidden');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,jsonb_set(current_setting('test.data')::jsonb,'{selected_activities,0,quantity}','-1'),NULL,NULL,false)$$,'22023','invalid_quotation_item','negative quantity rejected');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,jsonb_set(current_setting('test.data')::jsonb,'{selected_activities,0,price_per_person}','1.001'),NULL,NULL,false)$$,'22023','invalid_quotation_item','money precision rejected');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb||'{"discount":999}',NULL,NULL,false)$$,'22023','invalid_quotation_discount','discount cannot exceed gross');
SELECT extensions.throws_ok($$UPDATE public.quotes SET final_price=1 WHERE id=(current_setting('test.q')::jsonb->>'id')::uuid$$,'42501',NULL,'direct quote mutation denied');
SELECT public.save_customer('{"display_name":"Changed master","contact_name":"Changed master","vat_applicable":true,"billing_name":"Changed billing"}','96000000-0000-4000-8000-000000000010',1);
SELECT set_config('test.q2',public.save_quotation('96000000-0000-4000-8000-000000000012',(current_setting('test.q')::jsonb->>'id')::uuid,1,current_setting('test.data')::jsonb||'{"notes":"Revision two"}','96000000-0000-4000-8000-000000000010',1,false)::text,true);
SELECT extensions.is(current_setting('test.q2')::jsonb->>'vat_applicable','false','ordinary edit preserves customer VAT after master changes');
SELECT extensions.is((current_setting('test.q2')::jsonb->>'customer_version')::integer,1,'ordinary edit preserves quoted customer version');
SELECT extensions.is(public.save_quotation('96000000-0000-4000-8000-000000000011',NULL,0,current_setting('test.data')::jsonb,'96000000-0000-4000-8000-000000000010',1,false),current_setting('test.q')::jsonb,'old request replays old result after later revision');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),(current_setting('test.q')::jsonb->>'id')::uuid,1,current_setting('test.data')::jsonb,'96000000-0000-4000-8000-000000000010',1,false)$$,'PT409','quotation_version_conflict','stale quote edit rejected');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),(current_setting('test.q')::jsonb->>'id')::uuid,2,current_setting('test.data')::jsonb,'96000000-0000-4000-8000-000000000010',1,true)$$,'PT409','quotation_customer_version_conflict','stale explicit customer refresh rejected');
SELECT set_config('test.o',public.convert_quotation_to_order((current_setting('test.q2')::jsonb->>'id')::uuid,2)::text,true);
SELECT extensions.is((current_setting('test.o')::jsonb->>'total_price')::numeric,50.00::numeric,'order preserves discounted gross total');
SELECT extensions.is(current_setting('test.o')::jsonb->>'status',U&'\05DE\05D0\05D5\05E9\05E8','converted order retains normal approved status');
SELECT extensions.is(current_setting('test.o')::jsonb->>'payment_status',U&'\05DC\05D0 \05E9\05D5\05DC\05DD','converted order is unpaid');
SELECT extensions.is(jsonb_array_length(current_setting('test.o')::jsonb->'quotation_snapshot'->'selected_activities'),2,'conversion preserves both activity and product');
SELECT extensions.is(current_setting('test.o')::jsonb->>'vat_applicable','false','conversion takes quoted VAT not changed master');
SELECT extensions.is(current_setting('test.o')::jsonb->>'billing_institution_name','Quoted billing','conversion preserves manual billing override');
SELECT extensions.is((SELECT customer_version FROM public.customer_snapshots WHERE id=(current_setting('test.o')::jsonb->>'customer_snapshot_id')::uuid),1,'canonical order customer snapshot uses quoted customer version');
SELECT extensions.is(public.convert_quotation_to_order((current_setting('test.q2')::jsonb->>'id')::uuid,2)->>'id',current_setting('test.o')::jsonb->>'id','conversion exact existing order replay');
SELECT extensions.is((SELECT count(*) FROM public.orders WHERE quote_id=(current_setting('test.q')::jsonb->>'id')::uuid),1::bigint,'one order per quote');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),(current_setting('test.q')::jsonb->>'id')::uuid,2,current_setting('test.data')::jsonb,NULL,NULL,false)$$,'PT409','quotation_already_converted','converted quote cannot be rewritten');
SELECT extensions.throws_ok($$UPDATE public.orders SET quotation_snapshot='{}' WHERE id=(current_setting('test.o')::jsonb->>'id')::uuid$$,'42501','quotation_order_snapshot_immutable','order quoted contents immutable');
SELECT extensions.throws_ok($$UPDATE public.quotation_revisions SET data='{}'$$,'42501',NULL,'revision history cannot be directly edited');
SELECT set_config('test.legacy',public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb,NULL,NULL,false)::text,true);
SELECT extensions.is(current_setting('test.legacy')::jsonb->'vat_applicable','null'::jsonb,'manual unlinked VAT unknown');
SELECT set_config('test.legacy_order',public.convert_quotation_to_order((current_setting('test.legacy')::jsonb->>'id')::uuid,1)::text,true);
SELECT extensions.is(current_setting('test.legacy_order')::jsonb->'customer_snapshot_id','null'::jsonb,'manual legacy conversion stays unlinked');
INSERT INTO public.activities(id,name,price_per_person) VALUES ('96000000-0000-4000-8000-000000000031','Catalog activity one',12.35),('96000000-0000-4000-8000-000000000032','Catalog activity two',7.5);
SELECT set_config('test.activity_items','[{"item_type":"activity","activity_id":"96000000-0000-4000-8000-000000000031","activity_name":"Quoted activity one","price_per_person":12.35,"quantity":3,"description":"Quoted description"}]',true);
SELECT set_config('test.single_activity',public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb||jsonb_build_object('selected_activities',current_setting('test.activity_items')::jsonb),NULL,NULL,false)::text,true);
UPDATE public.activities SET name='Changed catalog name',price_per_person=999 WHERE id='96000000-0000-4000-8000-000000000031';
SELECT set_config('test.single_activity_order',public.convert_quotation_to_order((current_setting('test.single_activity')::jsonb->>'id')::uuid,1)::text,true);
SELECT extensions.is(current_setting('test.single_activity_order')::jsonb->>'activity_id','96000000-0000-4000-8000-000000000031','single activity conversion preserves valid compatibility FK');
SELECT extensions.is((current_setting('test.single_activity_order')::jsonb->>'total_price')::numeric,35.00::numeric,'single activity conversion preserves quoted quantity and discount after catalog edit');
SELECT extensions.is(current_setting('test.single_activity_order')::jsonb->'quotation_snapshot'->'selected_activities'->0->>'activity_name','Quoted activity one','single activity snapshot never enriches from changed catalog');
SELECT extensions.is((current_setting('test.single_activity_order')::jsonb->'quotation_snapshot'->'selected_activities'->0->>'quantity')::numeric,3::numeric,'single activity explicit quantity is independent of participants');
SELECT set_config('test.multi_activity',public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb||jsonb_build_object('selected_activities',current_setting('test.activity_items')::jsonb||'[{"item_type":"activity","activity_id":"96000000-0000-4000-8000-000000000032","activity_name":"Quoted activity two","price_per_person":7.5,"quantity":2}]'::jsonb),NULL,NULL,false)::text,true);
SELECT set_config('test.multi_activity_order',public.convert_quotation_to_order((current_setting('test.multi_activity')::jsonb->>'id')::uuid,1)::text,true);
SELECT extensions.is(current_setting('test.multi_activity_order')::jsonb->'activity_id','null'::jsonb,'multiple activities never pretend a single activity is the complete order');
SELECT extensions.is((current_setting('test.multi_activity_order')::jsonb->>'total_price')::numeric,50.00::numeric,'multiple activity-only total includes all quantities and discount');
SELECT extensions.is(current_setting('test.multi_activity_order')::jsonb->'quotation_snapshot'->'selected_activities',current_setting('test.multi_activity')::jsonb->'selected_activities','all activity-only items survive conversion exactly');
SELECT extensions.is(public.convert_quotation_to_order((current_setting('test.multi_activity')::jsonb->>'id')::uuid,1)->>'id',current_setting('test.multi_activity_order')::jsonb->>'id','activity-only conversion replay is idempotent');
SELECT extensions.is((SELECT count(*) FROM public.sales),0::bigint,'conversion creates no sales');
SELECT extensions.is((SELECT count(*) FROM public.payment_transactions),0::bigint,'conversion creates no payments');
SELECT extensions.is((SELECT count(*) FROM public.accounting_events),0::bigint,'conversion creates no accounting events');
SELECT extensions.is((SELECT quotation_version FROM public.quotes WHERE id='96000000-0000-4000-8000-000000000090'),0,'old quotes are not backfilled');
SELECT extensions.throws_ok($$SELECT public.convert_quotation_to_order('96000000-0000-4000-8000-000000000090',0)$$,'PT409','quotation_save_revision_required','legacy conversion explicitly requires saved revision');
SELECT set_config('test.saved_legacy',public.save_quotation(pg_catalog.gen_random_uuid(),'96000000-0000-4000-8000-000000000090',0,'{}',NULL,NULL,false)::text,true);
SELECT extensions.is((current_setting('test.saved_legacy')::jsonb->'selected_activities'->0->>'quantity')::numeric,10::numeric,'legacy omitted item quantity uses quoted participants');
SELECT extensions.is(current_setting('test.saved_legacy')::jsonb->'vat_applicable','null'::jsonb,'saving legacy preserves unknown VAT');
SELECT set_config('test.refresh',public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb,'96000000-0000-4000-8000-000000000010',2,true)::text,true);
SELECT extensions.is(current_setting('test.refresh')::jsonb->>'vat_applicable','true','explicit customer selection captures current VAT');
SELECT set_config('test.refreshed',public.save_quotation(pg_catalog.gen_random_uuid(),(current_setting('test.refresh')::jsonb->>'id')::uuid,1,'{}','96000000-0000-4000-8000-000000000010',2,true)::text,true);
SELECT extensions.is(current_setting('test.refreshed')::jsonb->>'client_name','Changed master','explicit refresh uses current master contact unless overridden');
INSERT INTO public.orders(client_name,client_phone,activity_date,num_participants,quote_id) VALUES('Manual linked order','0500000000','2026-11-01',1,(current_setting('test.refresh')::jsonb->>'id')::uuid);
SELECT extensions.throws_ok($$SELECT public.convert_quotation_to_order((current_setting('test.refreshed')::jsonb->>'id')::uuid,2)$$,'PT409','quotation_order_link_conflict','manual order link with missing converted pointer conflicts safely');
SELECT extensions.throws_ok($$INSERT INTO public.orders(client_name,client_phone,activity_date,num_participants,quote_id) VALUES('Duplicate','0500000000','2026-11-01',1,(current_setting('test.refresh')::jsonb->>'id')::uuid)$$,'23505',NULL,'unique index prevents racing duplicate link');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,jsonb_set(current_setting('test.data')::jsonb,'{selected_activities,0,quantity}','null'),NULL,NULL,false)$$,'22023','invalid_quotation_item','explicit null quantity rejected rather than fallback');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,jsonb_set(current_setting('test.data')::jsonb,'{selected_activities,0,images}','{}'),NULL,NULL,false)$$,'22023','invalid_quotation_item','malformed historical media rejected explicitly');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,jsonb_set(current_setting('test.data')::jsonb,'{selected_activities,0,price_per_person}','99999999.99'),NULL,NULL,false)$$,'22023','invalid_quotation_total','unrepresentable line total rejected');
SELECT set_config('test.cancelled',public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb||jsonb_build_object('status',U&'\05D1\05D5\05D8\05DC\05D4'),NULL,NULL,false)::text,true);
SELECT extensions.throws_ok($$SELECT public.convert_quotation_to_order((current_setting('test.cancelled')::jsonb->>'id')::uuid,1)$$,'PT409','quotation_cancelled','cancelled quotation cannot convert');
-- Force deferred revision checks before rollback so the rehearsal exercises them.
SET CONSTRAINTS ALL IMMEDIATE;
SET CONSTRAINTS ALL DEFERRED;
SELECT set_config('request.jwt.claims','{"role":"authenticated","sub":"96000000-0000-4000-8000-000000000002"}',true);
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb,NULL,NULL,false)$$,'42501','quotation_access_denied','cashier cannot save quotation');
SELECT extensions.throws_ok($$SELECT public.convert_quotation_to_order((current_setting('test.q')::jsonb->>'id')::uuid,2)$$,'42501','quotation_access_denied','cashier cannot convert quotation');
SELECT extensions.is((SELECT count(*) FROM public.quotation_revisions),0::bigint,'cashier cannot read quotation revisions');
RESET ROLE;
INSERT INTO auth.users(id,email) VALUES ('96000000-0000-4000-8000-000000000020','quotation-instructor@example.invalid'),('96000000-0000-4000-8000-000000000021','quotation-operations@example.invalid');
INSERT INTO public.instructors(id,full_name,phone,email) VALUES ('96000000-0000-4000-8000-000000000022','Quotation instructor','0500000000','quotation-instructor@example.invalid');
INSERT INTO public.orders(id,client_name,client_phone,activity_date,num_participants,instructor_id) VALUES ('96000000-0000-4000-8000-000000000023','Assigned ordinary order','0500000000','2026-11-01',1,'96000000-0000-4000-8000-000000000022');
UPDATE public.orders SET instructor_id='96000000-0000-4000-8000-000000000022' WHERE id=(current_setting('test.o')::jsonb->>'id')::uuid;
SELECT set_config('request.jwt.claims','{"role":"service_role"}',true);
UPDATE public.profiles SET role='operations' WHERE id='96000000-0000-4000-8000-000000000021';
SELECT set_config('request.jwt.claims','{"role":"authenticated","sub":"96000000-0000-4000-8000-000000000020"}',true);
SET LOCAL ROLE authenticated;
SELECT extensions.is((SELECT count(*) FROM public.quotes),1::bigint,'instructor sees only the correctly correlated linked quote');
SELECT extensions.is((SELECT id FROM public.quotes),(current_setting('test.q')::jsonb->>'id')::uuid,'instructor policy correlates orders.quote_id with outer quote id');
SELECT extensions.is((SELECT count(*) FROM public.quotation_revisions),0::bigint,'instructor gains no revision billing access');
SELECT extensions.throws_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb,NULL,NULL,false)$$,'42501','quotation_access_denied','instructor cannot save quotations');
SELECT extensions.throws_ok($$UPDATE public.orders SET quote_id=(current_setting('test.cancelled')::jsonb->>'id')::uuid WHERE id='96000000-0000-4000-8000-000000000023'$$,'42501','quotation_link_access_denied','instructor cannot steal unrelated quote visibility through ordinary assigned order');
SELECT extensions.is((SELECT count(*) FROM public.quotes),1::bigint,'failed instructor relink grants no additional quote visibility');
SELECT extensions.lives_ok($$UPDATE public.orders SET instructor_notified=true WHERE id='96000000-0000-4000-8000-000000000023'$$,'instructor notification update remains allowed');
SELECT extensions.is((SELECT instructor_notified FROM public.orders WHERE id='96000000-0000-4000-8000-000000000023'),true,'instructor notification change persists within test transaction');
SELECT set_config('request.jwt.claims','{"role":"authenticated","sub":"96000000-0000-4000-8000-000000000002"}',true);
SELECT extensions.throws_ok($$UPDATE public.orders SET quote_id=(current_setting('test.cancelled')::jsonb->>'id')::uuid WHERE id='96000000-0000-4000-8000-000000000023'$$,'42501','quotation_link_access_denied','cashier cannot relink existing order to quotation');
SELECT extensions.throws_ok($$INSERT INTO public.orders(client_name,client_phone,activity_date,num_participants,quote_id) VALUES('Forbidden cashier link','0500000000','2026-11-01',1,(current_setting('test.cancelled')::jsonb->>'id')::uuid)$$,'42501','quotation_link_access_denied','cashier cannot create an order with a quotation link');
SELECT extensions.throws_ok($$UPDATE public.orders SET quotation_snapshot='{}' WHERE id='96000000-0000-4000-8000-000000000023'$$,'42501','quotation_link_access_denied','cashier cannot inject a quotation snapshot into ordinary order');
SELECT extensions.lives_ok($$UPDATE public.orders SET notes='Ordinary cashier edit' WHERE id='96000000-0000-4000-8000-000000000023'$$,'ordinary cashier order edits retain existing permissions');
SELECT set_config('request.jwt.claims','{"role":"authenticated","sub":"96000000-0000-4000-8000-000000000021"}',true);
SELECT extensions.lives_ok($$SELECT public.save_quotation(pg_catalog.gen_random_uuid(),NULL,0,current_setting('test.data')::jsonb,NULL,NULL,false)$$,'operations can save quotations');
SELECT extensions.lives_ok($$UPDATE public.orders SET quote_id=(current_setting('test.cancelled')::jsonb->>'id')::uuid WHERE id='96000000-0000-4000-8000-000000000023'$$,'operations can explicitly associate an ordinary order with a quotation');
RESET ROLE;
SELECT set_config('request.jwt.claims','{"role":"service_role"}',true);
SET LOCAL ROLE service_role;
SELECT extensions.lives_ok($$UPDATE public.orders SET notes=notes WHERE id=(current_setting('test.o')::jsonb->>'id')::uuid$$,'service-role order update with unchanged quotation linkage remains allowed');
RESET ROLE;
SELECT set_config('request.jwt.claims','{"role":"authenticated","sub":"96000000-0000-4000-8000-000000000021"}',true);
SET LOCAL ROLE authenticated;
SET CONSTRAINTS ALL IMMEDIATE;
RESET ROLE;
SELECT extensions.throws_ok($$INSERT INTO public.quotes(client_name,client_phone,final_price) VALUES('Forged direct quote','0500000000',1)$$,'42501','quotation_revision_required','trigger prevents owner-level insertion without authoritative revision');
SELECT extensions.throws_ok($$UPDATE public.quotation_revisions SET data='{}'$$,'42501','quotation_artifact_immutable','revision mutation trigger protects privileged paths');
SET LOCAL ROLE anon;
SELECT extensions.throws_ok($$SELECT public.convert_quotation_to_order((current_setting('test.q')::jsonb->>'id')::uuid,2)$$,'42501',NULL,'anonymous role has no conversion execute grant');
RESET ROLE;
SELECT * FROM extensions.finish();
ROLLBACK;
