import { useState, useEffect } from "react";
import { supabase } from "@/api/supabaseClient";
import { toast } from "sonner";
import { useLocation } from "react-router-dom";
import ActivityGrid from "@/components/cashregister/ActivityGrid";
import Cart from "@/components/cashregister/Cart";
import PaymentScreen from "@/components/cashregister/PaymentScreen";
import ReceiptScreen from "@/components/cashregister/ReceiptScreen";

// SCREENS: menu | payment | receipt
export default function CashRegister() {
  const location = useLocation();
  const [activities, setActivities] = useState([]);
  const [loading, setLoading] = useState(true);
  const [cartItems, setCartItems] = useState([]);
  const [screen, setScreen] = useState("menu");
  const [paymentMethod, setPaymentMethod] = useState(null);
  const [receiptData, setReceiptData] = useState(null);

  useEffect(() => {
    const load = async () => {
      const { data, error } = await supabase
        .from('activities')
        .select('*')
        .eq('status', 'פעיל');
      if (error) {
        console.error('activities fetch error:', error);
        toast.error('שגיאה בטעינת הפעילויות');
      }
      setActivities(data ?? []);

      // Load prefilled item from URL (coming from Schedule)
      const params = new URLSearchParams(location.search);
      const prefill = params.get("prefill");
      if (prefill) {
        const item = JSON.parse(prefill);
        setCartItems([{ ...item, qty: item.qty || 1, customPrice: item.customPrice || 0 }]);
        setScreen("payment");
      }

      setLoading(false);
    };
    load();
  }, []);

  const addToCart = (activity) => {
    setCartItems(prev => {
      const existing = prev.find(i => i.id === activity.id);
      if (existing) return prev.map(i => i.id === activity.id ? { ...i, qty: i.qty + 1 } : i);
      return [...prev, { ...activity, qty: 1, customPrice: activity.price_per_person || 0 }];
    });
  };

  const updateQty = (id, delta) => {
    setCartItems(prev =>
      prev.map(i => i.id === id ? { ...i, qty: Math.max(1, i.qty + delta) } : i)
    );
  };

  const updatePrice = (id, price) => {
    setCartItems(prev => prev.map(i => i.id === id ? { ...i, customPrice: Number(price) } : i));
  };

  const removeItem = (id) => setCartItems(prev => prev.filter(i => i.id !== id));

  const total = cartItems.reduce((s, i) => s + i.customPrice * i.qty, 0);

  const handlePaymentConfirm = async (method) => {
    setPaymentMethod(method);
    const saleItems = cartItems.map(i => ({ id: i.id, name: i.name, qty: i.qty, customPrice: i.customPrice }));

    // Save sale to DB for reporting. receipt_number is generated by the DB
    // ('RCP-<seq>' DEFAULT) — never in JS — so we insert then read the row back.
    const { data, error } = await supabase
      .from('sales')
      .insert({
        items: saleItems,
        total,
        method,
        sale_date: new Date().toISOString().slice(0, 10),
      })
      .select()
      .single();

    let receiptNumber;
    if (error || !data) {
      console.error('sale insert error:', error);
      toast.error('שגיאה בשמירת המכירה — הקבלה מוצגת אך לא נשמרה');
      receiptNumber = `R${Date.now().toString().slice(-6)}`; // local fallback so the cashier still gets a receipt
    } else {
      receiptNumber = data.receipt_number;
    }

    const receipt = {
      items: cartItems,
      total,
      method,
      timestamp: new Date(),
      receiptNumber,
    };
    setReceiptData(receipt);
    setScreen("receipt");
  };

  const handleNewSale = () => {
    setCartItems([]);
    setScreen("menu");
    setPaymentMethod(null);
    setReceiptData(null);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen bg-slate-900">
        <div className="w-10 h-10 border-4 border-primary/30 border-t-primary rounded-full animate-spin" />
      </div>
    );
  }

  if (screen === "receipt") {
    return <ReceiptScreen receipt={receiptData} onNewSale={handleNewSale} />;
  }

  if (screen === "payment") {
    return <PaymentScreen total={total} cartItems={cartItems} onConfirm={handlePaymentConfirm} onBack={() => setScreen("menu")} />;
  }

  return (
    <div className="flex h-screen bg-white text-slate-900 overflow-hidden" dir="rtl">
      {/* Left: Activity Grid */}
      <div className="flex-1 overflow-y-auto p-4">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center text-white font-bold text-lg">א</div>
          <div>
            <h1 className="text-xl font-bold">אדוונצ׳ר — קופה</h1>
            <p className="text-slate-400 text-sm">בחר פעילות להוספה לסל</p>
          </div>
        </div>
        <ActivityGrid activities={activities} onAdd={addToCart} />
      </div>

      {/* Right: Cart */}
      <div className="w-80 border-r border-slate-200 flex flex-col bg-slate-50">
        <Cart
          items={cartItems}
          total={total}
          onUpdateQty={updateQty}
          onUpdatePrice={updatePrice}
          onRemove={removeItem}
          onCheckout={() => setScreen("payment")}
        />
      </div>
    </div>
  );
}