import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/api/supabaseClient";
import { Plus, Minus, Check } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const SITES = ["עכו", "טבריה", "נוף הגליל", "שטח"];

const emptyForm = {
  client_name: "", client_phone: "", client_email: "", organization: "",
  event_date: "", site: "", num_participants: "", notes: "",
  selected_activities: [], discount: "", status: "טיוטה",
};

export default function QuoteFormDialog({ open, onClose, quote, onSaved, prefill }) {
  const [form, setForm] = useState(emptyForm);
  const [activities, setActivities] = useState([]);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    const fetchActivities = async () => {
      const { data, error } = await supabase
        .from('activities')
        .select('*')
        .eq('status', 'פעיל');
      if (error) console.error('activities fetch error:', error);
      else setActivities(data ?? []);
    };
    fetchActivities();
  }, []);

  useEffect(() => {
    if (quote) {
      const enriched = (quote.selected_activities || []).map(sa => {
        const found = activities.find(a => a.id === sa.activity_id);
        return {
          ...sa,
          images: sa.images && sa.images.length > 0 ? sa.images : (found?.images || []),
          image_url: sa.image_url || found?.image_url || "",
        };
      });
      setForm({
        client_name:          quote.client_name || "",
        client_phone:         quote.client_phone || "",
        client_email:         quote.client_email || "",
        organization:         quote.organization || "",
        event_date:           quote.event_date || "",
        site:                 quote.site || "",
        num_participants:     quote.num_participants || "",
        notes:                quote.notes || "",
        selected_activities:  enriched,
        discount:             quote.discount || "",
        status:               quote.status || "טיוטה",
      });
    } else if (prefill) {
      setForm({ ...emptyForm, ...prefill });
    } else {
      setForm(emptyForm);
    }
  }, [quote, open, activities]);

  const toggleActivity = (activity) => {
    setForm(prev => {
      const exists = prev.selected_activities.find(a => a.activity_id === activity.id);
      if (exists) {
        return { ...prev, selected_activities: prev.selected_activities.filter(a => a.activity_id !== activity.id) };
      }
      return {
        ...prev,
        selected_activities: [...prev.selected_activities, {
          activity_id:      activity.id,
          activity_name:    activity.name,
          price_per_person: activity.price_per_person,
          duration_hours:   activity.duration_hours,
          image_url:        activity.image_url || "",
          images:           activity.images || [],
          description:      activity.description || "",
        }],
      };
    });
  };

  const participants  = Number(form.num_participants) || 0;
  const totalPrice    = form.selected_activities.reduce((sum, a) => sum + (a.price_per_person * participants), 0);
  const discount      = Number(form.discount) || 0;
  const finalPrice    = totalPrice - discount;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      const data = {
        ...form,
        num_participants: participants,
        discount,
        total_price:  totalPrice,
        final_price:  finalPrice,
        // Postgres rejects empty string for typed / CHECK-constrained columns.
        // event_date is DATE; site is TEXT CHECK (quotes_site_check).
        // Both columns are nullable, so null passes.
        event_date: form.event_date || null,
        site:       form.site       || null,
      };

      let error;
      if (quote) {
        // Preserve the existing quote_number — remove from payload to avoid accidental change
        delete data.quote_number;
        ({ error } = await supabase.from('quotes').update(data).eq('id', quote.id));
      } else {
        // quote_number auto-generated by DB sequence (QUO-xxxx)
        ({ error } = await supabase.from('quotes').insert(data));
      }

      if (error) {
        console.error('save quote error:', error);
        toast.error('שגיאה בשמירת ההצעה');
        return;
      }

      onSaved();
      onClose();
    } catch (err) {
      console.error('handleSubmit error:', err);
      toast.error('שגיאה בשמירת ההצעה');
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto" dir="rtl">
        <DialogHeader>
          <DialogTitle>{quote ? "עריכת הצעת מחיר" : "הצעת מחיר חדשה"}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-5 mt-2">
          {/* Client details */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>שם הלקוח *</Label>
              <Input value={form.client_name} onChange={e => setForm(p => ({...p, client_name: e.target.value}))} required />
            </div>
            <div>
              <Label>טלפון *</Label>
              <Input value={form.client_phone} onChange={e => setForm(p => ({...p, client_phone: e.target.value}))} required />
            </div>
            <div>
              <Label>אימייל</Label>
              <Input value={form.client_email} onChange={e => setForm(p => ({...p, client_email: e.target.value}))} />
            </div>
            <div>
              <Label>ארגון / חברה</Label>
              <Input value={form.organization} onChange={e => setForm(p => ({...p, organization: e.target.value}))} />
            </div>
            <div>
              <Label>תאריך אירוע מוצע</Label>
              <Input type="date" value={form.event_date} onChange={e => setForm(p => ({...p, event_date: e.target.value}))} />
            </div>
            <div>
              <Label>אתר</Label>
              <Select value={form.site} onValueChange={v => setForm(p => ({...p, site: v}))}>
                <SelectTrigger><SelectValue placeholder="בחר אתר" /></SelectTrigger>
                <SelectContent>{SITES.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div>
              <Label>מספר משתתפים</Label>
              <Input type="number" min="1" value={form.num_participants} onChange={e => setForm(p => ({...p, num_participants: e.target.value}))} />
            </div>
          </div>

          {/* Activities selection */}
          <div>
            <Label className="text-base font-semibold">בחר פעילויות</Label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-2">
              {activities.map(activity => {
                const selected = form.selected_activities.find(a => a.activity_id === activity.id);
                return (
                  <button
                    type="button"
                    key={activity.id}
                    onClick={() => toggleActivity(activity)}
                    className={cn(
                      "flex items-start gap-3 p-3 rounded-xl border text-right transition-all",
                      selected ? "border-primary bg-primary/5 shadow-sm" : "border-border hover:bg-muted"
                    )}
                  >
                    {activity.image_url && (
                      <img src={activity.image_url} alt={activity.name} className="w-12 h-12 rounded-lg object-cover flex-shrink-0" />
                    )}
                    <div className="flex-1 min-w-0">
                      <p className="font-medium text-sm">{activity.name}</p>
                      <p className="text-xs text-muted-foreground">{activity.duration_hours} שע׳ • {activity.price_per_person}₪ לאדם</p>
                      {participants > 0 && (
                        <p className="text-xs font-semibold text-primary mt-0.5">{(activity.price_per_person * participants).toLocaleString()}₪ סה״כ</p>
                      )}
                    </div>
                    {selected && <Check className="w-4 h-4 text-primary flex-shrink-0 mt-0.5" />}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Price summary */}
          {form.selected_activities.length > 0 && participants > 0 && (
            <div className="bg-muted/50 rounded-xl p-4 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">סה״כ לפני הנחה:</span>
                <span className="font-semibold">{totalPrice.toLocaleString()}₪</span>
              </div>
              <div className="flex items-center justify-between gap-3">
                <span className="text-sm text-muted-foreground">הנחה (₪):</span>
                <Input type="number" min="0" value={form.discount} onChange={e => setForm(p => ({...p, discount: e.target.value}))} className="w-32 text-left" placeholder="0" />
              </div>
              <div className="flex justify-between text-base font-bold border-t border-border pt-2">
                <span>מחיר סופי:</span>
                <span className="text-primary">{finalPrice.toLocaleString()}₪</span>
              </div>
            </div>
          )}

          <div>
            <Label>הערות</Label>
            <Textarea value={form.notes} onChange={e => setForm(p => ({...p, notes: e.target.value}))} rows={2} placeholder="הערות נוספות ללקוח..." />
          </div>

          <div className="flex gap-3 justify-end pt-2">
            <Button type="button" variant="outline" onClick={onClose}>ביטול</Button>
            <Button type="submit" disabled={saving}>{saving ? "שומר..." : quote ? "עדכון" : "צור הצעה"}</Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
