import moment from 'moment';
import { orderConfirmationModel } from '@/lib/orderConfirmation';
import { BRAND, ORDER_TERMS_INTRO, ORDER_TERMS, ORDER_TERMS_RETURN, SIGNATURE_BLOCK, MOBILE_CONTACT, SAFETY_TITLE, SAFETY_GROUP_FIELD, SAFETY_RULES, SAFETY_DECLARATION, SAFETY_SIGNATURE, SAFETY_MINORS_HEADER, SAFETY_MINORS_TEXT, SAFETY_CONTACT } from '@/lib/orderDocText';
const money = value => value === null ? 'לא תועד' : `${Number(value).toLocaleString('he-IL',{maximumFractionDigits:2,minimumFractionDigits:2})} ₪`;
const date = value => value ? moment(value).format('DD/MM/YYYY') : 'לא תועד';
function Numbered({values}) { return <div className="space-y-2">{values.map((text,index)=><p key={index} data-pdf-block className="text-sm leading-7"><strong>{index+1}. </strong>{text}</p>)}</div>; }
export default function OrderConfirmationDocument({data}) {
 const m=orderConfirmationModel(data),c=m.customer;
 return <article dir="rtl" className="bg-white text-slate-800" style={{width:794,padding:32,fontFamily:"'Heebo', Arial, sans-serif",overflowWrap:'anywhere'}}>
  <header data-pdf-block className="flex justify-between items-center border-b border-blue-100 pb-5 mb-6"><div><h1 className="text-3xl font-bold">אישור הזמנה</h1><p>{m.orderNumber}</p><p className="text-sm text-slate-500">תאריך ההזמנה: {date(m.savedAt)}</p></div><img src="/shafan-logo.jpg" alt={BRAND.name} style={{width:180,height:'auto'}} /></header>
  <section data-pdf-block className="grid grid-cols-2 gap-4 mb-6"><div className="bg-slate-50 rounded-xl p-4"><h2 className="font-semibold mb-2">פרטי לקוח</h2><p>{c.client_name || 'לא תועד'}</p><p>{c.organization}</p><p dir="ltr" className="text-right">{c.client_phone}</p><p>{c.client_email}</p></div><div className="bg-slate-50 rounded-xl p-4"><h2 className="font-semibold mb-2">פרטי האירוע</h2><p>{date(m.date)}</p>{m.start && <p>{m.start.slice(0,5)}{m.end ? '–'+m.end.slice(0,5) : ''}</p>}<p>{m.site}</p>{m.participants !== null && <p>{m.participants} משתתפים</p>}</div></section>
  <section data-pdf-block className="mb-6 text-sm"><h2 className="font-semibold">פרטי חיוב שמורים</h2><p>{c.billing_institution_name || 'שם לחיוב לא תועד'}</p>{c.billing_company_id && <p>ח.פ / ע.מ: {c.billing_company_id}</p>}<p>{c.billing_accounting_email}</p><p>{[c.billing_address_line,c.billing_city,c.billing_postal_code,c.billing_country_code].filter(Boolean).join(', ')}</p><p className="mt-2">{m.vatLabel}</p></section>
  <section className="space-y-4"><h2 data-pdf-block className="text-lg font-semibold">פעילויות ומוצרים</h2>{m.items.map((item,index)=><div key={index} data-pdf-block className="border border-slate-200 rounded-xl p-4"><div data-pdf-block className="flex justify-between gap-4"><div><h3 className="font-bold">{item.name}</h3><p className="text-sm">{item.type==='product' ? 'מוצר' : item.type==='activity' ? 'פעילות' : 'פריט שמור'}</p><p>כמות: {item.quantity ?? 'לא תועדה'} · מחיר יחידה: {money(item.unit)}</p>{item.duration>0 && <p>{item.duration} שעות</p>}<p>{item.site}{item.date ? ' · '+date(item.date) : ''}</p></div><strong className="shrink-0">{money(item.total)}</strong></div>{item.description && <p data-pdf-block className="whitespace-pre-wrap text-sm leading-7 mt-2">{item.description}</p>}</div>)}</section>
  <section data-pdf-block className="border-t border-slate-200 pt-4 mt-6 space-y-1"><p>סטטוס תשלום: {m.paymentStatus}</p>{m.subtotal !== null && <p>סכום הפריטים השמור בהצעה: {money(m.subtotal)}</p>}{m.discount>0 && <p>הנחה שמורה בהצעה: {money(m.discount)}</p>}<p className="font-bold text-xl">סה״כ ההזמנה: {money(m.total)}</p><p>{m.vatLabel}</p></section>
  {[['הערות להזמנה',m.notes],['הערות שמורות מהצעת המחיר',m.quotationNotes]].filter(([,text])=>text).map(([title,text])=><section key={title} className="bg-amber-50 p-4 mt-5"><h2 data-pdf-block className="font-semibold">{title}</h2><p data-pdf-block className="whitespace-pre-wrap text-sm leading-7">{text}</p></section>)}
  <section className="border-t border-slate-200 pt-5 mt-6"><h2 data-pdf-block className="font-semibold mb-3">{ORDER_TERMS_INTRO}</h2><Numbered values={[m.vatLabel,...ORDER_TERMS.slice(1)]}/><p data-pdf-block className="text-sm mt-3">{ORDER_TERMS_RETURN}</p></section>
  <section data-pdf-block className="border-t border-slate-200 pt-5 mt-6 space-y-3"><p>{SIGNATURE_BLOCK.ack}</p>{SIGNATURE_BLOCK.fields.map(text=><p key={text}>{text}</p>)}{SIGNATURE_BLOCK.closing.map(text=><p key={text}>{text}</p>)}<p className="text-sm">{MOBILE_CONTACT}</p></section>
  <section className="border-t border-blue-100 pt-6 mt-8"><h2 data-pdf-block className="text-2xl font-bold mb-4">{SAFETY_TITLE}</h2><p data-pdf-block className="mb-4">{SAFETY_GROUP_FIELD}</p><Numbered values={SAFETY_RULES}/>{SAFETY_DECLARATION.map((text,index)=><p key={index} data-pdf-block className="text-sm leading-7 mt-4">{text}</p>)}<p data-pdf-block className="mt-5">{SAFETY_SIGNATURE}</p><div data-pdf-block className="mt-6 space-y-3"><h3 className="font-bold">{SAFETY_MINORS_HEADER}</h3><p className="text-sm leading-7">{SAFETY_MINORS_TEXT}</p><p>{SAFETY_SIGNATURE}</p></div></section>
  <footer data-pdf-block className="border-t border-blue-100 mt-6 pt-4 text-xs text-center text-slate-500">{SAFETY_CONTACT}</footer>
 </article>;
}
